### ISSUE TITLE
Holes in the rendered model

### ISSUE THREAD

**Issue by FeliceGeracitano** [michead/vscode-mesh-viewer#1]
Small issue that produce checkered a flag theme for some previews :)

![holes_render](https://user-images.githubusercontent.com/6695231/34213394-05738546-e597-11e7-9a0b-ab020d28825f.png)

**Comment by michead** [comment]
Hi @FeliceGeracitano, thanks a lot for this bug report.
I was able to reproduce that issue -- it was due to lack of support for quads, which has been added in `v0.0.4`. 👍
